# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: book-catalog:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 
        env:
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          value: "postgresql://book_catalog_x3zi_user:bvgbCTfRiJ1I6imjcW2jNG972N6LuLdP@dpg-crvkrr1u0jms73dpjcvg-a.oregon-postgres.render.com/book_catalog_x3zi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 80                  
      targetPort: 8080          
      nodePort: 30001
